# Generated by Django 4.2.4 on 2023-08-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_larger_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(upload_to='listing_images/normal'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='larger_image',
            field=models.ImageField(blank=True, null=True, upload_to='listing_images/larger'),
        ),
    ]
